function [d2min, d2max] = blockij_euclidean_d2_limits(coord, coord_norm2, idx_i, idx_j, is_diagonal_block)
%[d2min, d2max] = blockij_d2_limits(coord, coord_norm2, idx_i, idx_j, is_diagonal_block)
%   Find max and min d2 for block pair (i,j)

d2 = blockij_euclidean_d2(...
    coord(idx_i,:), ...
    coord(idx_j,:), ...
    coord_norm2(idx_i,:), ...
    coord_norm2(idx_j,:), ...
    is_diagonal_block);
d2max = max(d2,[],'all');
d2(d2 <= 0) = Inf;
d2min = min(d2,[],'all');

end